CREATE TABLE thoughtful_entries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT,
    pseudonym TEXT,
    journal_id INTEGER REFERENCES thoughtful_journals(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);
